name: run only production related SW

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build sender
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o productionsender DataSender.c

    - name: build receiver
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o productionreceiver receiver/reciever.c receiver/CalcMinMax.c receiver/CalcMovingAvg.c receiver/statistics.c
      
    - name: run
      run: ./productionsender | ./productionreceiver        
